[settings]
dotfiles.root = "~/.dotfiles"
dotfiles.default_mode = "symlink"

[dotfiles]
"~/.zshrc/source_common" = { line = "source $HOME/.dotfiles/zsh/.zshrc.common" }
"~/.termcap" = { source = "~/.dotfiles/termcap/.termcap" }
"~/.emacs" = { source = "~/.dotfiles/emacs/.emacs" }
"~/.emacs.d" = { source = "~/.dotfiles/emacs/.emacs.d" }
"~/.tmux.conf" = { source = "~/.dotfiles/tmux/.tmux.conf" }
"~/.vimrc" = { source = "~/.dotfiles/vim/.vimrc" }
"~/.config/ghostty/config" = { source = "~/.dotfiles/ghostty/config" }

